### PR TITLE
Making folder paths to relative

### PR DESCRIPTION
**Pull request by juvander**
As requested in #24 

I believe these will do the same as for VB version. There was some nuget errors so could not get this project to compile.

### CODE REVIEW

**Comment by juvander** [comment]
Any comment for this, go/no-go?
Fixed those nuget reference errors as well so they are waiting next to come over :)

**Comment by valadas** [comment]
It is a bit hard to review at a glance with all those commits and I currently don't have a proper test bed for this module. Will get to it when possible. Thanks.

**Comment by valadas** [comment]
Oh, I think I know what happend, you submitted this pull request from your master branch instead of a branch specific for this issue because I see other pull requests from you with the same commits.

**Comment by juvander** [comment]
That is very well possible, but those other ones should be now separated. Will see your comments on those later today.

**Comment by valadas** [comment]
Replaced by #41 as a cherry pick.

**Pull request closed without merging**
