### PR TITLE
#58 Keep backward compatibility for upgraded modules that contains some customized storage locations

### LINKED ISSUE #58: Breaking change regarding the files storage location
## Describe the bug
After upgrade the module from 3.5.6 to 4.1.1, customized file downloads are using to a bad location.

## Software Versions
- DNN: 09.13.00
- Module: 04.01.01

## To Reproduce
1. Upgrade an old website using the 3.5.6 version to the 4.1.1
2. Click on the download link for a file listed by an existing module (created with the old version)
3. The error message is: [FileNotFoundException: Could not find file 'C:\Website\Portals\0\Repository\...

## Expected behavior
User should obtain the selected file when clicking on the download link.

## Additional context
This problem occurs when the file storage location have been customized with an old Repository module version.
In this cas, the correct path is 'C:\Website\Portals\0\Download\...' instead of the default ''C:\Website\Portals\0\Repository\...'.

### PR DESCRIPTION
**Pull request by stetard**
### Description of PR...
Changed the code to take into account some potentials customized storage locations for upgraded modules.

## Changes made
- Settings Form: add the ability to display customized locations instead of the defaults
- Helpers: introduce Default values for the 3 storage locations and compare them to the current module settings to use the corrects values.

## PR Template Checklist

- [X] Fixes Bug
- [ ] Feature solution
- [ ] Other

Close #58

### CODE REVIEW

**Comment by maduranga001** [comment]
Please, can somebody share the DLL file which includes all the last changes? Thank you so much.

**Comment by stetard** [comment]
@maduranga001 you can download my dll at https://www.aricie.com/DotNetNuke.Modules.Repository.dll_patched.zip if needed.

**Comment by stetard** [comment]
Sorry, it's a wrong url.
The correct url is https://download.aricie.com/DotNetNuke.Modules.Repository.dll_patched.zip

**Comment by valadas** [comment]
I have just released a new version here if you want the full package https://github.com/DNNCommunity/DNN.Repository/releases/tag/v4.1.2

**Pull request merged**
